# Generated by Django 4.2.13 on 2024-06-08 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("objects", "0014_defaultobject_defaultcharacter_defaultexit_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpaceDB",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("db_key", models.CharField(db_index=True, max_length=80)),
                ("db_category", models.CharField(blank=True, max_length=80, null=True)),
                ("db_name", models.CharField(blank=True, max_length=80, null=True)),
                ("db_desc", models.TextField(blank=True, null=True)),
                ("db_transmat", models.TextField(blank=True, null=True)),
                (
                    "db_dock_room",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                (
                    "db_mass",
                    models.DecimalField(
                        decimal_places=100, default=0.0, max_digits=200
                    ),
                ),
                (
                    "db_radius",
                    models.DecimalField(
                        decimal_places=100, default=0.0, max_digits=200
                    ),
                ),
                (
                    "db_x_coord",
                    models.DecimalField(
                        decimal_places=100, default=0.0, max_digits=200
                    ),
                ),
                (
                    "db_y_coord",
                    models.DecimalField(
                        decimal_places=100, default=0.0, max_digits=200
                    ),
                ),
                (
                    "db_z_coord",
                    models.DecimalField(
                        decimal_places=100, default=0.0, max_digits=200
                    ),
                ),
                (
                    "db_x_vel",
                    models.DecimalField(
                        decimal_places=100, default=0.0, max_digits=200
                    ),
                ),
                (
                    "db_y_vel",
                    models.DecimalField(
                        decimal_places=100, default=0.0, max_digits=200
                    ),
                ),
                (
                    "db_z_vel",
                    models.DecimalField(
                        decimal_places=100, default=0.0, max_digits=200
                    ),
                ),
                (
                    "db_orbital_radius",
                    models.DecimalField(
                        decimal_places=100, default=0.0, max_digits=200
                    ),
                ),
                (
                    "db_orbital_period",
                    models.DecimalField(
                        decimal_places=100, default=0.0, max_digits=200
                    ),
                ),
                (
                    "db_inclination",
                    models.DecimalField(
                        decimal_places=100, default=0.0, max_digits=200
                    ),
                ),
                ("db_in_space", models.BooleanField(default=False)),
                (
                    "db_date_created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="date created"
                    ),
                ),
                (
                    "db_item",
                    models.ForeignKey(
                        help_text="the object that this space entry represents in the evennia db",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="objects.objectdb",
                        verbose_name="object",
                    ),
                ),
                (
                    "db_orbiting_body",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text="the object that this space entry orbits",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="space.spacedb",
                        verbose_name="space object",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SpaceContactDB",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("db_key", models.CharField(db_index=True, max_length=80)),
                (
                    "db_history_name",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                (
                    "db_date_updated",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                (
                    "db_mass",
                    models.DecimalField(
                        decimal_places=100, default=0.0, max_digits=200
                    ),
                ),
                (
                    "db_radius",
                    models.DecimalField(
                        decimal_places=100, default=0.0, max_digits=200
                    ),
                ),
                (
                    "db_attraction",
                    models.DecimalField(
                        decimal_places=100, default=0.0, max_digits=200
                    ),
                ),
                (
                    "db_x_coord",
                    models.DecimalField(
                        decimal_places=100, default=0.0, max_digits=200
                    ),
                ),
                (
                    "db_y_coord",
                    models.DecimalField(
                        decimal_places=100, default=0.0, max_digits=200
                    ),
                ),
                (
                    "db_z_coord",
                    models.DecimalField(
                        decimal_places=100, default=0.0, max_digits=200
                    ),
                ),
                (
                    "db_x_vel",
                    models.DecimalField(
                        decimal_places=100, default=0.0, max_digits=200
                    ),
                ),
                (
                    "db_y_vel",
                    models.DecimalField(
                        decimal_places=100, default=0.0, max_digits=200
                    ),
                ),
                (
                    "db_z_vel",
                    models.DecimalField(
                        decimal_places=100, default=0.0, max_digits=200
                    ),
                ),
                (
                    "db_distance",
                    models.DecimalField(
                        decimal_places=100, default=0.0, max_digits=200
                    ),
                ),
                (
                    "db_bearing",
                    models.DecimalField(
                        decimal_places=100, default=0.0, max_digits=200
                    ),
                ),
                (
                    "db_inclination",
                    models.DecimalField(
                        decimal_places=100, default=0.0, max_digits=200
                    ),
                ),
                (
                    "db_approach_bearing",
                    models.DecimalField(
                        decimal_places=100, default=0.0, max_digits=200
                    ),
                ),
                (
                    "db_helm",
                    models.ForeignKey(
                        help_text="the object that this space entry represents in the evennia db",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="objects.objectdb",
                        verbose_name="object",
                    ),
                ),
                (
                    "db_space_obj",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text="the object that this space entry represents",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="space.spacedb",
                        verbose_name="spaceobject",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
