# Generated by Django 4.2.13 on 2024-06-09 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("space", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="spacecontactdb",
            options={
                "verbose_name": "Help Entry",
                "verbose_name_plural": "Help Entries",
            },
        ),
        migrations.AlterModelOptions(
            name="spacedb",
            options={
                "verbose_name": "Help Entry",
                "verbose_name_plural": "Help Entries",
            },
        ),
    ]
