# Generated by Django 4.2.13 on 2024-06-09 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("space", "0002_alter_spacecontactdb_options_alter_spacedb_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="spacecontactdb",
            options={
                "verbose_name": "Space Contact",
                "verbose_name_plural": "Space Contacts",
            },
        ),
        migrations.AlterModelOptions(
            name="spacedb",
            options={
                "verbose_name": "Space Object",
                "verbose_name_plural": "Space Objects",
            },
        ),
    ]
