# Generated by Django 4.2.13 on 2024-06-09 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("space", "0003_alter_spacecontactdb_options_alter_spacedb_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="spacecontactdb",
            options={
                "verbose_name": "SpaceContact",
                "verbose_name_plural": "SpaceContacts",
            },
        ),
        migrations.AlterModelOptions(
            name="spacedb",
            options={
                "verbose_name": "SpaceObject",
                "verbose_name_plural": "SpaceObjects",
            },
        ),
    ]
