# Generated by Django 4.2.13 on 2024-06-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("space", "0004_alter_spacecontactdb_options_alter_spacedb_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="spacedb",
            name="db_ascii_art",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
